version: "3.7"
services:
 app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: jtntest
    container_name: jtntest-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - jtntest

 db:
    image: mysql:5.7
    container_name: jtntest-db
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
    volumes:
    - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
    - jtntest

 nginx:
    image: nginx:1.17-alpine
    container_name: jtntest-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - jtntest

networks:
  jtntest:
    driver: bridge
